// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hijvwhscgpfhnercpecn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpanZ3aHNjZ3BmaG5lcmNwZWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzUxMDgsImV4cCI6MjA1ODIxMTEwOH0.j6QA2kUfuQcHmtJXlJJRAdYr9ywoZE08PY__mu9iEkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);